name: docs

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      SENTRY_NATIVE_INSTALL: ~/sentry-native

    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: "recursive"
      - name: Install curl
        run: sudo apt install libcurl4-openssl-dev
      - name: Get sentry-native commit
        id: sentry_native
        run:
          echo ::set-output name=version::$(git submodule status | cut -d ' ' -f
          2)
      - name: Cache sentry-native
        uses: actions/cache@v2
        with:
          path: ~/sentry-native
          key: ${{ runner.os }}-${{ steps.sentry_native.outputs.version }}
      - name: Documentation
        env:
          RUSTDOCFLAGS: -Z unstable-options --enable-index-page
        run:
          cargo -v doc --features nightly --no-deps --document-private-items
          --workspace
      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc/
          TARGET_FOLDER: master/doc/
          CLEAN: true
