name: docs

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
      - name: Cache rustc version
        uses: actions/cache@v2
        with:
          path: ~/rustc-version.txt
          key: documentation-${{ runner.os }}-${{ matrix.rust.channel }}
      - name: Compare rustc versions
        if: github.event_name == 'schedule'
        run: "! diff -u ~/rustc-version.txt <(rustc -V)"
      - name: Save new rustc version
        run: rustc -V > ~/rustc-version.txt
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: recursive
      - name: Install Curl
        run: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev
      - name: Get sentry-native commit
        id: sentry_native
        run:
          echo "::set-output name=version::$(git submodule status | cut -d ' '
          -f 2)"
      - name: Cache sentry-native
        uses: actions/cache@v2
        with:
          path: ~/sentry-native
          key:
            ${{ runner.os }}-${{ steps.sentry_native.outputs.version }}-true-${{
            hashFiles('sentry-contrib-native-sys/build.rs') }}
      - name: Set SENTRY_NATIVE_INSTALL
        run: echo >>$GITHUB_ENV SENTRY_NATIVE_INSTALL=$HOME/sentry-native
      - name: Documentation
        env:
          RUSTDOCFLAGS: -Z unstable-options --enable-index-page
        run:
          cargo -v doc --features transport-custom,nightly --no-deps --workspace
          --exclude dylib
      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc/
          GIT_CONFIG_NAME: github-actions
          GIT_CONFIG_EMAIL: github-actions@github.com
          TARGET_FOLDER: master/doc/
          CLEAN: true
