name: format

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Prettier
        run: npm install --no-save prettier prettier-plugin-toml
      - name: Prettier
        run: npx prettier -l .

  rustfmt:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly

    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Rust Formatting
        run: cargo fmt -v -- --check
